from pathlib import Path
from typing import Any, Callable, Literal, Mapping
from . import Router, Verification

class HomeFixture:
    home: Path
    env: dict[str, str]
    def close(self) -> None: ...
class UpstreamFixture:
    origin: str
    requests: list[dict[str, Any]]
    def close(self) -> None: ...
class VendorFixture:
    binary: Path
    directory: Path
    env: dict[str, str]
    def close(self) -> None: ...

def temporary_home() -> HomeFixture: ...
def mock_upstream(handler: Callable[[dict[str, Any]], dict[str, Any]] | None = ...) -> UpstreamFixture: ...
def vendor_stub(*, name: str = ..., version: str = ..., output: str = ..., exit_code: int = ...) -> VendorFixture: ...
def verify_contracts(*, router: Router | None = ..., areas: tuple[str, ...] | list[str] = ..., linux: bool = ..., repository: str | Path | None = ..., output: str | Path | None = ..., client_versions: Literal['installed', 'ci', 'latest'] = ..., deadline: float = ..., require_parity: bool = ..., env: Mapping[str, str] | None = ...) -> Verification: ...
